name: Auto Commit

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 06:50 AM UTC+8 (22:50 UTC)
    - cron: "50 22 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "songjay8@gmail.com"
          git config --local user.name "0xjayfi"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away and keep building"
          git push